# Use the official Alpine Linux image as the base image
FROM postgres:16-alpine

# Set environment variables for PostgreSQL
ENV LANG en_US.utf8
ENV PGDATA /var/lib/postgresql/data

# Switch to the postgres user
USER postgres

# Create a directory for PostgreSQL data (if not exists)
RUN mkdir -p "$PGDATA" && chown -R postgres:postgres "$PGDATA"

# Expose the default PostgreSQL port
EXPOSE 5432

# CMD to start PostgreSQL without reinitiating the database
CMD ["postgres", "-D", "/var/lib/postgresql/data"]
